### ISSUE TITLE
DevTools never ends "Resetting"

### ISSUE THREAD

**Issue by pabloHoc** [amitnovick/xstate-devtools#18]
Hi! First of all, thank you for developing this amazing tool. I'm having the exact same problem of this issue: #13, DevTools doesn't render anything. I tried every solution mentioned: there's no error on DevTools inspector, I'm using `{ devTools: true}`,  `injected.js` is loaded, already tried the breakpoint hack but didn't work, and I'm using the latest version. 

I don't think the problem is in the machine config, it never worked actually, and I tried with really simple ones (like the examples from the docs).

Any other alternative I could try? Thanks!

**Comment by pabloHoc** [comment]
Nevermind, I don't know what I did but it started working. I can't believe it did it 2 minutes after posting the issue, I tried without success for the last two days. Restarting React hot reloading seems to work.

**Comment by mulholo** [comment]
Can I suggest reopening this? I'm getting the same issue.

**Comment by JackCA** [comment]
I am as well

**Comment by hrafnkellpalsson** [comment]
I get this error on and off

**Comment by Dema** [comment]
I've had this error in Next.js when I left `devtools: true` when rendering on server. After I changed to
```
devTools:
      process.env.NODE_ENV === "development" && typeof window !== "undefined",
```
 it started to work perfectly

**Comment by baeharam** [comment]
Same issue, **must be re-opened** @amitnovick

**Comment by jzarzeckis** [comment]
Bump
