### ISSUE TITLE
Can't click on event

### ISSUE THREAD

**Issue by davydof** [amitnovick/xstate-devtools#26]
Hello guys!
@davidkpiano @amitnovick 

Thanks for amazing library xstate and dev tools!

Today I got issue: I can't click on the event.
The events are blocked and have been disabled.

Could you please fix it or assist to help me if I missed something?

![image](https://user-images.githubusercontent.com/10529679/80744924-1544bb00-8b28-11ea-8170-da5974396e24.png)

xstate-devtools version:
`0.5.3`

Google Chrome versions:
Version `84.0.4131.0` (Official Build) canary (64-bit)

Version `81.0.4044.129` (Official Build) (64-bit)

**Comment by davidkpiano** [comment]
The dev tools are meant to visualize the machine, not control it.

**Comment by davydof** [comment]
@davidkpiano 
thanks for fast reply :)

![image](https://user-images.githubusercontent.com/10529679/80747186-b41ee680-8b2b-11ea-9443-f74d8b0cb614.png)
here I can click on event, "send" it to Machine and simulate the behavior.
https://xstate.js.org/viz/

1. why I can't do the same in devtools?
2. how I can mimic(emit) the `send` event like here https://xstate.js.org/viz?
3. how I can debug huge complex app with many xstate machines that are combined?

**Comment by davidkpiano** [comment]
> why I can't do the same in devtools?

Because dev tools reflects actual machines used in your application, not prototype machines.

**Comment by davydof** [comment]
so sad, it can be amazing feature
